name: Build and Test

on: [push]

jobs:
  test:

    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        node-version: [10]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm ci, lint, and build
      run: |
        npm install
        npm run lint
        npm run build
    - name: npm test
      run: |
        npm test
      env:
        CI: true
